name: parkmycar_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  http: ^1.2.2
  # path: ^1.8.0
  parkmycar_shared:
    path: '../parkmycar_shared'
  parkmycar_client_shared:
    path: '../parkmycar_client_shared'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
